import { subDays, format } from 'date-fns'

// ─── DEMO GOALS ───────────────────────────────────────────────────────────────

export const DEMO_GOALS = [
  {
    id: 'goal-1',
    title: 'Get lean and athletic',
    description: 'Reach 12% body fat and build functional strength for daily life.',
    category: 'HEALTH',
    status: 'ACTIVE',
    priority: 1,
    targetDate: new Date('2026-06-01'),
    progress: 42,
    color: '#10b981',
    emoji: '💪',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date(),
    milestones: [
      { id: 'ms-1', goalId: 'goal-1', title: 'Lose first 5 lbs', status: 'COMPLETED', order: 1, dueDate: null, description: null, completedAt: new Date() },
      { id: 'ms-2', goalId: 'goal-1', title: 'Workout 4x/week consistently', status: 'IN_PROGRESS', order: 2, dueDate: null, description: null, completedAt: null },
      { id: 'ms-3', goalId: 'goal-1', title: 'Hit 15% body fat', status: 'PENDING', order: 3, dueDate: null, description: null, completedAt: null },
      { id: 'ms-4', goalId: 'goal-1', title: 'Reach 12% body fat', status: 'PENDING', order: 4, dueDate: null, description: null, completedAt: null },
    ],
    habits: [{ id: 'habit-1', title: 'Workout', category: 'FITNESS', frequency: 'DAILY', trackingType: 'BINARY', color: '#10b981', currentStreak: 12, longestStreak: 21, totalCompletions: 89, isActive: true, goalId: 'goal-1' }],
    tasks: [
      { id: 'task-g1', title: 'Book personal trainer session', status: 'TODO', priority: 'MEDIUM', tags: [], goalId: 'goal-1' },
    ],
  },
  {
    id: 'goal-2',
    title: 'Read 12 books this year',
    description: 'One book a month. Focus on business, psychology, and science.',
    category: 'LEARNING',
    status: 'ACTIVE',
    priority: 2,
    targetDate: new Date('2026-12-31'),
    progress: 33,
    color: '#8b5cf6',
    emoji: '📚',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date(),
    milestones: [
      { id: 'ms-5', goalId: 'goal-2', title: 'Read 3 books (Q1)', status: 'COMPLETED', order: 1, dueDate: null, description: null, completedAt: new Date() },
      { id: 'ms-6', goalId: 'goal-2', title: 'Read 6 books (Q2)', status: 'IN_PROGRESS', order: 2, dueDate: null, description: null, completedAt: null },
      { id: 'ms-7', goalId: 'goal-2', title: 'Read 9 books (Q3)', status: 'PENDING', order: 3, dueDate: null, description: null, completedAt: null },
      { id: 'ms-8', goalId: 'goal-2', title: 'Read 12 books (Q4)', status: 'PENDING', order: 4, dueDate: null, description: null, completedAt: null },
    ],
    habits: [],
    tasks: [],
  },
  {
    id: 'goal-3',
    title: 'Launch FORGE to 1,000 users',
    description: 'Build, ship, and grow a productized SaaS to its first major milestone.',
    category: 'BUSINESS',
    status: 'ACTIVE',
    priority: 1,
    targetDate: new Date('2026-09-01'),
    progress: 15,
    color: '#6366f1',
    emoji: '🚀',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date(),
    milestones: [
      { id: 'ms-9', goalId: 'goal-3', title: 'Ship MVP', status: 'IN_PROGRESS', order: 1, dueDate: null, description: null, completedAt: null },
      { id: 'ms-10', goalId: 'goal-3', title: 'First 100 signups', status: 'PENDING', order: 2, dueDate: null, description: null, completedAt: null },
      { id: 'ms-11', goalId: 'goal-3', title: 'First paying customer', status: 'PENDING', order: 3, dueDate: null, description: null, completedAt: null },
      { id: 'ms-12', goalId: 'goal-3', title: '1,000 active users', status: 'PENDING', order: 4, dueDate: null, description: null, completedAt: null },
    ],
    habits: [],
    tasks: [
      { id: 'task-g3-1', title: 'Finish core modules', status: 'IN_PROGRESS', priority: 'URGENT', tags: ['dev'], goalId: 'goal-3' },
      { id: 'task-g3-2', title: 'Set up Supabase auth', status: 'TODO', priority: 'HIGH', tags: ['dev'], goalId: 'goal-3' },
    ],
  },
  {
    id: 'goal-4',
    title: 'Learn conversational Spanish',
    description: 'Achieve B1 level and hold a 10-minute conversation by year end.',
    category: 'LEARNING',
    status: 'ACTIVE',
    priority: 3,
    targetDate: new Date('2026-12-01'),
    progress: 18,
    color: '#f59e0b',
    emoji: '🇪🇸',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date(),
    milestones: [
      { id: 'ms-13', goalId: 'goal-4', title: 'Complete A1 Duolingo path', status: 'COMPLETED', order: 1, dueDate: null, description: null, completedAt: new Date() },
      { id: 'ms-14', goalId: 'goal-4', title: 'Reach 100-day Duolingo streak', status: 'IN_PROGRESS', order: 2, dueDate: null, description: null, completedAt: null },
    ],
    habits: [],
    tasks: [],
  },
  {
    id: 'goal-5',
    title: 'Save $30k emergency fund',
    description: 'Full 6-month financial runway. Peace of mind, freedom to take risks.',
    category: 'FINANCE',
    status: 'ACTIVE',
    priority: 2,
    targetDate: new Date('2026-10-01'),
    progress: 55,
    color: '#10b981',
    emoji: '💰',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date(),
    milestones: [
      { id: 'ms-15', goalId: 'goal-5', title: 'Save $10k', status: 'COMPLETED', order: 1, dueDate: null, description: null, completedAt: new Date() },
      { id: 'ms-16', goalId: 'goal-5', title: 'Save $20k', status: 'IN_PROGRESS', order: 2, dueDate: null, description: null, completedAt: null },
    ],
    habits: [],
    tasks: [],
  },
]

// ─── DEMO HABITS ──────────────────────────────────────────────────────────────

export const DEMO_HABITS = [
  {
    id: 'habit-1',
    title: 'Workout',
    category: 'FITNESS',
    frequency: 'DAILY',
    trackingType: 'BINARY',
    color: '#10b981',
    emoji: '🏋️',
    currentStreak: 12,
    longestStreak: 21,
    totalCompletions: 89,
    isActive: true,
    goalId: 'goal-1',
    todayLog: { completed: false },
  },
  {
    id: 'habit-2',
    title: 'Meditate',
    category: 'MINDFULNESS',
    frequency: 'DAILY',
    trackingType: 'DURATION',
    targetValue: 10,
    unit: 'minutes',
    color: '#8b5cf6',
    emoji: '🧘',
    currentStreak: 5,
    longestStreak: 30,
    totalCompletions: 64,
    isActive: true,
    goalId: null,
    todayLog: { completed: true },
  },
  {
    id: 'habit-3',
    title: 'Read',
    category: 'LEARNING',
    frequency: 'DAILY',
    trackingType: 'DURATION',
    targetValue: 30,
    unit: 'minutes',
    color: '#6366f1',
    emoji: '📖',
    currentStreak: 8,
    longestStreak: 45,
    totalCompletions: 112,
    isActive: true,
    goalId: 'goal-2',
    todayLog: { completed: false },
  },
  {
    id: 'habit-4',
    title: 'Spanish lesson',
    category: 'LEARNING',
    frequency: 'DAILY',
    trackingType: 'BINARY',
    color: '#f59e0b',
    emoji: '🇪🇸',
    currentStreak: 44,
    longestStreak: 44,
    totalCompletions: 44,
    isActive: true,
    goalId: 'goal-4',
    todayLog: { completed: true },
  },
  {
    id: 'habit-5',
    title: 'No phone morning',
    category: 'PRODUCTIVITY',
    frequency: 'DAILY',
    trackingType: 'BINARY',
    color: '#3b82f6',
    emoji: '📵',
    currentStreak: 3,
    longestStreak: 14,
    totalCompletions: 28,
    isActive: true,
    goalId: null,
    todayLog: { completed: false },
  },
  {
    id: 'habit-6',
    title: 'Cold shower',
    category: 'HEALTH',
    frequency: 'DAILY',
    trackingType: 'BINARY',
    color: '#06b6d4',
    emoji: '🚿',
    currentStreak: 7,
    longestStreak: 21,
    totalCompletions: 52,
    isActive: true,
    goalId: null,
    todayLog: { completed: false },
  },
]

// ─── DEMO HABIT LOGS (for heatmap) ────────────────────────────────────────────

export const DEMO_HABIT_LOGS = Array.from({ length: 90 }, (_, i) => {
  const date = format(subDays(new Date(), 89 - i), 'yyyy-MM-dd')
  return {
    date,
    completed: Math.random() > 0.25, // ~75% completion rate
  }
})

// ─── DEMO TASKS ───────────────────────────────────────────────────────────────

export const DEMO_TASKS = [
  {
    id: 'task-1',
    title: 'Finish FORGE Today dashboard',
    description: 'Complete all components and wire up demo data',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    energy: 'HIGH',
    estimatedMinutes: 120,
    scheduledFor: new Date(),
    tags: ['dev', 'forge'],
    goalId: 'goal-3',
  },
  {
    id: 'task-2',
    title: 'Write weekly newsletter',
    status: 'TODO',
    priority: 'HIGH',
    energy: 'MEDIUM',
    estimatedMinutes: 45,
    scheduledFor: new Date(),
    tags: ['content'],
    goalId: null,
  },
  {
    id: 'task-3',
    title: 'Review Q1 budget vs actuals',
    status: 'TODO',
    priority: 'MEDIUM',
    energy: 'LOW',
    estimatedMinutes: 30,
    scheduledFor: new Date(),
    tags: ['finance'],
    goalId: 'goal-5',
  },
  {
    id: 'task-4',
    title: 'Call mom',
    status: 'COMPLETED',
    priority: 'HIGH',
    estimatedMinutes: 20,
    scheduledFor: new Date(),
    tags: [],
    goalId: null,
    completedAt: new Date(),
  },
  {
    id: 'task-5',
    title: 'Meal prep for the week',
    status: 'TODO',
    priority: 'MEDIUM',
    energy: 'LOW',
    estimatedMinutes: 60,
    scheduledFor: new Date(),
    tags: ['health'],
    goalId: 'goal-1',
  },
  {
    id: 'task-6',
    title: 'Read chapter 4 of Almanack',
    status: 'TODO',
    priority: 'LOW',
    energy: 'LOW',
    estimatedMinutes: 30,
    scheduledFor: new Date(),
    tags: ['reading'],
    goalId: 'goal-2',
  },
]

// ─── DEMO TIME BLOCKS ─────────────────────────────────────────────────────────

export const DEMO_TIME_BLOCKS = [
  { id: 'tb-1', dailyPlanId: 'today', title: 'Morning routine', startTime: '07:00', endTime: '08:00', category: 'PERSONAL', color: '#10b981', isCompleted: true },
  { id: 'tb-2', dailyPlanId: 'today', title: 'Deep work — FORGE', startTime: '08:00', endTime: '10:00', category: 'WORK', color: '#6366f1', isCompleted: false },
  { id: 'tb-3', dailyPlanId: 'today', title: 'Break + walk', startTime: '10:00', endTime: '10:30', category: 'BREAK', color: '#f59e0b', isCompleted: false },
  { id: 'tb-4', dailyPlanId: 'today', title: 'Newsletter writing', startTime: '10:30', endTime: '11:30', category: 'WORK', color: '#6366f1', isCompleted: false },
  { id: 'tb-5', dailyPlanId: 'today', title: 'Lunch', startTime: '12:00', endTime: '13:00', category: 'BREAK', color: '#f59e0b', isCompleted: false },
  { id: 'tb-6', dailyPlanId: 'today', title: 'Budget review', startTime: '13:00', endTime: '13:30', category: 'WORK', color: '#6366f1', isCompleted: false },
  { id: 'tb-7', dailyPlanId: 'today', title: 'Workout', startTime: '17:30', endTime: '18:30', category: 'HEALTH', color: '#10b981', isCompleted: false },
  { id: 'tb-8', dailyPlanId: 'today', title: 'Spanish lesson', startTime: '19:00', endTime: '19:30', category: 'LEARNING', color: '#8b5cf6', isCompleted: false },
  { id: 'tb-9', dailyPlanId: 'today', title: 'Read + journal', startTime: '21:00', endTime: '22:00', category: 'PERSONAL', color: '#ec4899', isCompleted: false },
]

// ─── DEMO NOTES ───────────────────────────────────────────────────────────────

export const DEMO_NOTES = [
  {
    id: 'note-1',
    title: 'The compounding power of daily habits',
    content: 'Every action you take is a vote for the type of person you want to become. You don\'t rise to the level of your goals, you fall to the level of your systems. — James Clear\n\nApplication: instead of thinking "I want to get fit", think "I am a person who moves every day".',
    type: 'QUOTE',
    tags: ['habits', 'mindset', 'james-clear'],
    isPinned: true,
    isFavorite: true,
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: 'note-2',
    title: 'SaaS idea: AI-powered meal planner',
    content: 'People hate meal planning because it requires thinking and creativity every week. What if an AI learned your preferences, macros, and schedule and auto-generated weekly meal plans with a grocery list?\n\nMonetization: $12/month. Target: fitness-conscious professionals aged 25-40.\nMVP: simple form + GPT-4 output + Notion-style recipe cards.',
    type: 'IDEA',
    tags: ['startup', 'saas', 'ai', 'health'],
    isPinned: false,
    isFavorite: false,
    createdAt: new Date('2026-04-01'),
    updatedAt: new Date('2026-04-10'),
  },
  {
    id: 'note-3',
    title: 'FORGE GTM strategy notes',
    content: 'Distribution is the moat, not the product.\n\nChannels to test:\n1. Twitter/X build-in-public thread series\n2. ProductHunt launch (need to time with feature completeness)\n3. Newsletter sponsorships in productivity/startup space\n4. Referral program with XP bonuses\n\nPricing hypothesis: Free tier (limited habits/goals) → Pro $10/month → Team $25/seat',
    type: 'BUSINESS',
    tags: ['forge', 'growth', 'strategy'],
    isPinned: true,
    isFavorite: false,
    createdAt: new Date('2026-04-10'),
    updatedAt: new Date('2026-04-20'),
  },
  {
    id: 'note-4',
    title: 'Book notes: The Psychology of Money',
    content: 'Key idea: your personal history with money shapes your financial behavior more than any spreadsheet.\n\nMorgan Housel\'s best insight: wealth is what you don\'t see. The car not bought, the watch not worn. True wealth is financial assets that haven\'t been converted to stuff.\n\nReferenced in: The Psychology of Money by Morgan Housel',
    type: 'NOTE',
    tags: ['finance', 'books', 'psychology'],
    isPinned: false,
    isFavorite: true,
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-22'),
  },
]

// ─── DEMO WEEKLY DATA (for charts) ────────────────────────────────────────────

export const DEMO_WEEKLY_DATA = [
  { week: 'Feb 3', score: 58, tasksCompleted: 12, habitsCompleted: 28, journalEntries: 4 },
  { week: 'Feb 10', score: 63, tasksCompleted: 15, habitsCompleted: 32, journalEntries: 5 },
  { week: 'Feb 17', score: 55, tasksCompleted: 10, habitsCompleted: 25, journalEntries: 3 },
  { week: 'Feb 24', score: 70, tasksCompleted: 18, habitsCompleted: 38, journalEntries: 6 },
  { week: 'Mar 3', score: 74, tasksCompleted: 20, habitsCompleted: 40, journalEntries: 7 },
  { week: 'Mar 10', score: 68, tasksCompleted: 16, habitsCompleted: 35, journalEntries: 5 },
  { week: 'Mar 17', score: 79, tasksCompleted: 22, habitsCompleted: 42, journalEntries: 7 },
  { week: 'Mar 24', score: 82, tasksCompleted: 24, habitsCompleted: 44, journalEntries: 7 },
]

// ─── DEMO RADAR DATA ──────────────────────────────────────────────────────────

export const DEMO_RADAR_DATA = [
  { area: 'Health', score: 75 },
  { area: 'Career', score: 60 },
  { area: 'Learning', score: 80 },
  { area: 'Finance', score: 55 },
  { area: 'Relationships', score: 70 },
  { area: 'Mind', score: 85 },
]
